export const countries = [
  "Nigeria",
  "Ethiopia",
  "Egypt",
  "Democratic Republic of the Congo",
  "Tanzania",
  "South Africa",
  "Kenya",
  "Uganda",
  "Algeria",
  "Sudan",
  "Morocco",
  "Angola",
  "Mozambique",
  "Ghana",
  "Madagascar",
  "Cameroon",
  "Côte d'Ivoire",
  "Niger",
  "Burkina Faso",
  "Mali",
];

export const state = {
  Nigeria: {
    state: [
      "Abia",
      "Adamawa",
      "Akwa Ibom",
      "Anambra",
      "Bauchi",
      "Bayelsa",
      "Benue",
      "Borno",
      "Cross River",
      "Delta",
      "Ebonyi",
      "Edo",
      "Ekiti",
      "Enugu",
      "Gombe",
      "Imo",
      "Jigawa",
      "Kaduna",
      "Kano",
      "Katsina",
      "Kebbi",
      "Kogi",
      "Kwara",
      "Lagos",
      "Nasarawa",
      "Niger",
      "Ogun",
      "Ondo",
      "Osun",
      "Oyo",
      "Plateau",
      "Rivers",
      "Sokoto",
      "Taraba",
      "Yobe",
      "Zamfara",
      "Federal Capital Territory",
    ],
  },
};
