export interface HeroDataType {
  id: number;
  category: string;
  image: string[];
  name: string;
  description: string;
  brand: string;
  keyword: string[];
  price: number;
  discount: number;
  stockQuantity: number;
}
export let HeroData: HeroDataType[] = [
  {
    id: 1,
    category: "fullrangespeaker",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576523/Amplifier/frs1_cjtnzn.png",
    ],
    name: "SP-137",
    description: "15 Inch / 4000watt / Pure Acostic / 75.5 coil /Double magnet",
    price: 1300000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "full range speaker",
      "15 inch",
      "4000 watt",
      "pure acoustic",
      "double magnet",
      "75.5 coil",
      "speaker",
      "audio",
      "sound system",
    ],
    brand: "soundprince",
  },
  {
    id: 2,
    category: "fullrangespeaker",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576523/Amplifier/frs2_ytcvtf.png",
    ],
    name: "SP-215GF",
    description: "15 Inch / 4000watt / Ply wood / 100 coil /Big Magnet",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "full range speaker",
      "15 inch",
      "4000 watt",
      "plywood",
      "big magnet",
      "100 coil",
      "speaker",
      "audio",
      "sound system",
    ],
    brand: "soundprince",
  },
  {
    id: 3,
    category: "fullrangespeaker",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576524/Amplifier/frs3_vlhhve.png",
    ],
    name: "SP-515",
    description:
      "18 Inch / 6000watt / Pure Acostic / 100 coil /passive speaker",
    price: 2500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "full range speaker",
      "18 inch",
      "6000 watt",
      "pure acoustic",
      "passive speaker",
      "100 coil",
      "speaker",
      "audio",
      "high power",
    ],
    brand: "soundprince",
  },
  {
    id: 4,
    category: "fullrangespeaker",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576530/Amplifier/frs4_jdoid2.png",
    ],
    name: "SP-215GF",
    description: "15 Inch / 4000watt / Ply wood / 100 coil /Big Magnet",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "full range speaker",
      "15 inch",
      "4000 watt",
      "plywood",
      "big magnet",
      "100 coil",
      "speaker",
      "audio",
      "sound system",
    ],
    brand: "soundprince",
  },
  {
    id: 5,
    category: "fullrangespeaker",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576532/Amplifier/frs5_lm7p54.png",
    ],
    name: "SP-215GF",
    description:
      "18 Inch / 6000watt / Pure Acostic / 100 coil /passive speaker",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "full range speaker",
      "18 inch",
      "6000 watt",
      "pure acoustic",
      "passive speaker",
      "100 coil",
      "speaker",
      "audio",
      "high power",
    ],
    brand: "soundprince",
  },
  {
    id: 6,
    category: "newspeakerarrival",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576369/Amplifier/nsa1_bk2obg.png",
    ],
    name: "SP-227",
    description: "15 Inch / 4000watt / Pure Acostic / 100 coil /Big magnet",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "new speaker",
      "15 inch",
      "4000 watt",
      "pure acoustic",
      "big magnet",
      "100 coil",
      "speaker",
      "audio",
      "latest",
      "new arrival",
    ],
    brand: "soundprince",
  },
  {
    id: 7,
    category: "newspeakerarrival",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576371/Amplifier/nsa2_foup8a.png",
    ],
    name: "SP-228",
    description: "15 Inch / 4000watt / Pure Acostic / 100 coil /Double Magnet",
    price: 2200000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "new speaker",
      "15 inch",
      "4000 watt",
      "pure acoustic",
      "double magnet",
      "100 coil",
      "speaker",
      "audio",
      "latest",
      "new arrival",
    ],
    brand: "soundprince",
  },
  {
    id: 8,
    category: "newspeakerarrival",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576371/Amplifier/nsa3_w7vehh.png",
    ],
    name: "SP-229",
    description: "15 Inch / 4000watt / Pure Acostic / 100 coil /Double Magnet",
    price: 2400000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "new speaker",
      "15 inch",
      "4000 watt",
      "pure acoustic",
      "double magnet",
      "100 coil",
      "speaker",
      "audio",
      "latest",
      "new arrival",
    ],
    brand: "soundprince",
  },
  {
    id: 9,
    category: "newspeakerarrival",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576373/Amplifier/nsa4_fzqvcy.png",
    ],
    name: "SP-25",
    description: "15 Inch / 2000watt / Pure Acostic / 75.5 coil /Big magnet",
    price: 1100000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "new speaker",
      "15 inch",
      "2000 watt",
      "pure acoustic",
      "big magnet",
      "75.5 coil",
      "speaker",
      "audio",
      "latest",
      "new arrival",
    ],
    brand: "soundprince",
  },
  {
    id: 10,
    category: "newspeakerarrival",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576382/Amplifier/nsa5_lguhka.png",
    ],
    name: "SP-20",
    description:
      "5 Inch / 2000watt / Pure Acostic body / 99.9 coil / passive speaker",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "new speaker",
      "5 inch",
      "2000 watt",
      "pure acoustic",
      "passive speaker",
      "99.9 coil",
      "speaker",
      "audio",
      "compact",
      "new arrival",
    ],
    brand: "soundprince",
  },
  {
    id: 11,
    category: "singlesub",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576056/Amplifier/ss1_vyszzf.png",
    ],
    name: "SP-18",
    description:
      "18 Inch / 2000watt / ply wood / 99.9 coil /8 Ohms/ Passive sub",
    price: 1200000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "single subwoofer",
      "18 inch",
      "2000 watt",
      "plywood",
      "passive sub",
      "99.9 coil",
      "8 ohms",
      "bass",
      "subwoofer",
    ],
    brand: "soundprince",
  },
  {
    id: 12,
    category: "singlesub",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576048/Amplifier/ss2_nglgtx.png",
    ],
    name: "SP-18GF",
    description:
      "18 Inch / 2000watt / Ply wood / 100 coil /8 Ohms/ Passive sub",
    price: 1300000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "single subwoofer",
      "18 inch",
      "2000 watt",
      "plywood",
      "passive sub",
      "100 coil",
      "8 ohms",
      "bass",
      "subwoofer",
    ],
    brand: "soundprince",
  },
  {
    id: 13,
    category: "singlesub",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576047/Amplifier/ss3_jfomaf.png",
    ],
    name: "SP-18AX",
    description:
      "18 Inch / 2000watt / Ply wood / 120 coil /8 Ohms/ Passive sub",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "single subwoofer",
      "18 inch",
      "2000 watt",
      "plywood",
      "passive sub",
      "120 coil",
      "8 ohms",
      "bass",
      "subwoofer",
    ],
    brand: "soundprince",
  },
  {
    id: 14,
    category: "singlesub",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576047/Amplifier/ss4_p4iffy.png",
    ],
    name: "SP-318",
    description:
      "18 Inch / 2000watt / Pure Acostic / 95.5 coil /8 Ohms/ Passive sub",
    price: 1100000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "single subwoofer",
      "18 inch",
      "2000 watt",
      "pure acoustic",
      "passive sub",
      "95.5 coil",
      "8 ohms",
      "bass",
      "subwoofer",
    ],
    brand: "soundprince",
  },
  {
    id: 15,
    category: "singlesub",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752576045/Amplifier/ss5_wdnvxu.png",
    ],
    name: "SP-18 FX",
    description:
      "18 Inch / 2000watt / Ply wood / 140 coil /8 Ohms/ Passive sub",
    price: 1400000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "single subwoofer",
      "18 inch",
      "2000 watt",
      "plywood",
      "passive sub",
      "140 coil",
      "8 ohms",
      "bass",
      "subwoofer",
      "fx",
    ],
    brand: "soundprince",
  },
  {
    id: 16,
    category: "doublesub",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573328/Amplifier/ds1_nnw69a.png",
    ],
    name: "POW-221B",
    description:
      "21 Inch / 5000watt / ply wood / 150 coil /8 Ohms/ Passive sub",
    price: 4000000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "double subwoofer",
      "21 inch",
      "5000 watt",
      "plywood",
      "passive sub",
      "150 coil",
      "8 ohms",
      "bass",
      "subwoofer",
      "power",
      "high power",
    ],
    brand: "rave",
  },
  {
    id: 17,
    category: "doublesub",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573332/Amplifier/ds2_uevo0u.png",
    ],
    name: "SP-218 DR",
    description:
      "18 Inch / 4000watt / Ply wood / 100 coil /8 Ohms/ Passive sub",
    price: 2200000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "double subwoofer",
      "18 inch",
      "4000 watt",
      "plywood",
      "passive sub",
      "100 coil",
      "8 ohms",
      "bass",
      "subwoofer",
    ],
    brand: "soundprince",
  },
  {
    id: 18,
    category: "doublesub",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573333/Amplifier/ds3_sgrc7g.png",
    ],
    name: "SP-218",
    description:
      "18 Inch / 4000watt / Ply wood / 100 coil /8 Ohms/ Passive sub",
    price: 1600000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "double subwoofer",
      "18 inch",
      "4000 watt",
      "plywood",
      "passive sub",
      "100 coil",
      "8 ohms",
      "bass",
      "subwoofer",
    ],
    brand: "soundprince",
  },
  {
    id: 19,
    category: "doublesub",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573333/Amplifier/ds5_mrotnt.png",
    ],
    name: "SP-218 CRV",
    description:
      "Doublesub / 18 Inch / 4600watt / plywood / 120 coil /8 Ohms/ Passive sub",
    price: 3500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "double subwoofer",
      "18 inch",
      "4600 watt",
      "plywood",
      "passive sub",
      "120 coil",
      "8 ohms",
      "bass",
      "subwoofer",
      "crv",
    ],
    brand: "soundprince",
  },
  {
    id: 20,
    category: "doublesub",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573338/Amplifier/ds4_wy2diu.png",
    ],
    name: "SP-218 GF",
    description:
      "Doublesub / 18 Inch / 4000watt / plywood / 100 coil /8 Ohms/ Passive sub",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "double subwoofer",
      "18 inch",
      "4000 watt",
      "plywood",
      "passive sub",
      "100 coil",
      "8 ohms",
      "bass",
      "subwoofer",
    ],
    brand: "soundprince",
  },
  {
    id: 21,
    category: "amplifier",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752572811/Amplifier/am1_q15mxy.png",
    ],
    name: "SPX7-5000",
    description: "4 channel / 1250watt per channel",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "amplifier",
      "4 channel",
      "1250 watt per channel",
      "power amplifier",
      "audio amplifier",
      "multi channel",
      "sound system",
    ],
    brand: "soundprince",
  },
  {
    id: 22,
    category: "amplifier",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752572815/Amplifier/am2_vkq9zu.png",
    ],
    name: "SP4500X",
    description: "2 channel / 4500watt",
    price: 850000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "amplifier",
      "2 channel",
      "4500 watt",
      "power amplifier",
      "audio amplifier",
      "stereo",
      "sound system",
    ],
    brand: "soundprince",
  },
  {
    id: 23,
    category: "amplifier",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752572825/Amplifier/am3_qc4ham.png",
    ],
    name: "SP4000",
    description: "2 channel / 3500watt",
    price: 450000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "amplifier",
      "2 channel",
      "3500 watt",
      "power amplifier",
      "audio amplifier",
      "stereo",
      "sound system",
    ],
    brand: "soundprince",
  },
  {
    id: 24,
    category: "amplifier",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752572830/Amplifier/am4_sfsklc.png",
    ],
    name: "SPX2800S",
    description: "2 channel / 3500watt",
    price: 650000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "amplifier",
      "2 channel",
      "3500 watt",
      "power amplifier",
      "audio amplifier",
      "stereo",
      "sound system",
    ],
    brand: "soundprince",
  },
  {
    id: 25,
    category: "amplifier",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752572832/Amplifier/am5_z2k3tb.png",
    ],
    name: "SPX4000S",
    description: "2 channel / 500watt",
    price: 900000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "amplifier",
      "2 channel",
      "500 watt",
      "power amplifier",
      "audio amplifier",
      "stereo",
      "sound system",
    ],
    brand: "soundprince",
  },
  {
    id: 26,
    category: "flatmixer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752575006/Amplifier/fm1_zz5m2e.png",
    ],
    name: "CM-16",
    description: "15 Inch / 2000watt / Pure Acostic / 100 coil /Big magnet",
    price: 1365000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "flat mixer",
      "15 inch",
      "2000 watt",
      "pure acoustic",
      "100 coil",
      "big magnet",
      "mixer",
      "audio mixer",
      "console",
    ],
    brand: "rave",
  },
  {
    id: 27,
    category: "flatmixer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752575011/Amplifier/fm2_qscpwq.png",
    ],
    name: "CMX-1642",
    description: "15 Inch / 4800watt / Pure Acostic / 100 coil /Double magnet",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "flat mixer",
      "15 inch",
      "4800 watt",
      "pure acoustic",
      "100 coil",
      "double magnet",
      "mixer",
      "audio mixer",
      "console",
    ],
    brand: "rave",
  },
  {
    id: 28,
    category: "flatmixer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752575013/Amplifier/fm3_tyfgif.png",
    ],
    name: "SP4000",
    description: "15 Inch / 2000watt / Pure Acostic / 100 coil /Big magnet",
    price: 2500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "flat mixer",
      "15 inch",
      "2000 watt",
      "pure acoustic",
      "100 coil",
      "big magnet",
      "mixer",
      "audio mixer",
      "console",
    ],
    brand: "soundprince",
  },
  {
    id: 29,
    category: "flatmixer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752575004/Amplifier/fm4_lredjo.png",
    ],
    name: "SPX2800S",
    description: "15 Inch / 4000watt / Ply wood / 100 coil /Big magnet",
    price: 365000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "flat mixer",
      "15 inch",
      "4000 watt",
      "plywood",
      "100 coil",
      "big magnet",
      "mixer",
      "audio mixer",
      "console",
    ],
    brand: "soundprince",
  },
  {
    id: 30,
    category: "flatmixer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752575000/Amplifier/fm5_gzjevu.png",
    ],
    name: "SPX4000S",
    description: "15 Inch / 4800watt / Pure Acostic / 100 coil /Double magnet",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "flat mixer",
      "15 inch",
      "4800 watt",
      "pure acoustic",
      "100 coil",
      "double magnet",
      "mixer",
      "audio mixer",
      "console",
    ],
    brand: "soundprince",
  },
  {
    id: 31,
    category: "floormixer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752574538/Amplifier/frm1_up8cgr.png",
    ],
    name: "SP-12FX",
    description: "12 Inch / 2000watt / Ply wood / 100 coil /Big magnet",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "floor mixer",
      "12 inch",
      "2000 watt",
      "plywood",
      "100 coil",
      "big magnet",
      "mixer",
      "audio mixer",
      "floor console",
      "fx",
    ],
    brand: "soundprince",
  },
  {
    id: 32,
    category: "floormixer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752574539/Amplifier/frm2_pfrrjt.png",
    ],
    name: "SP-12M",
    description: "12 Inch / 700watt / Pure Acostic / 100 coil /Double magnet",
    price: 800000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "floor mixer",
      "12 inch",
      "700 watt",
      "pure acoustic",
      "100 coil",
      "double magnet",
      "mixer",
      "audio mixer",
      "floor console",
    ],
    brand: "soundprince",
  },
  {
    id: 33,
    category: "floormixer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752574544/Amplifier/frm3_ool2yx.png",
    ],
    name: "SP-12MTX",
    description: "12 Inch / 1000watt / Pure Acostic / 100 coil /Big magnet",
    price: 1000000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "floor mixer",
      "12 inch",
      "1000 watt",
      "pure acoustic",
      "100 coil",
      "big magnet",
      "mixer",
      "audio mixer",
      "floor console",
      "mtx",
    ],
    brand: "soundprince",
  },
  {
    id: 34,
    category: "floormixer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752574542/Amplifier/frm4_npjci7.png",
    ],
    name: "SP-15/15A",
    description: "12 Inch / 2000watt / Plastic body / 100 coil /Big magnet",
    price: 1000000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "floor mixer",
      "12 inch",
      "2000 watt",
      "plastic body",
      "100 coil",
      "big magnet",
      "mixer",
      "audio mixer",
      "floor console",
    ],
    brand: "soundprince",
  },
  {
    id: 35,
    category: "floormixer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752574540/Amplifier/frm5_unvtrg.png",
    ],
    name: "SP-15FX",
    description: "15 Inch / 2000watt / Pure Acostic / 100 coil /Double magnet",
    price: 1800000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "floor mixer",
      "15 inch",
      "2000 watt",
      "pure acoustic",
      "100 coil",
      "double magnet",
      "mixer",
      "audio mixer",
      "floor console",
      "fx",
    ],
    brand: "soundprince",
  },
  {
    id: 36,
    category: "equalizer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573497/Amplifier/e1_vdmuqe.png",
    ],
    name: "DBX-224XL",
    description:
      "18 Inch / 2000watt / Pure Acostic / 99.9 coil /8 Ohms/ Passive sub",
    price: 1000000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "equalizer",
      "dbx",
      "audio processor",
      "eq",
      "sound processing",
      "frequency control",
      "audio equipment",
    ],
    brand: "rave",
  },
  {
    id: 37,
    category: "equalizer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573501/Amplifier/e2_zintvd.png",
    ],
    name: "DBX-EQX 231",
    description:
      "18 Inch / 2000watt / Pure Acostic / 100 coil /8 Ohms/ Passive sub",
    price: 1300000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "equalizer",
      "dbx",
      "audio processor",
      "eq",
      "sound processing",
      "frequency control",
      "audio equipment",
      "eqx",
    ],
    brand: "rave",
  },
  {
    id: 38,
    category: "equalizer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573502/Amplifier/e3_l9apam.png",
    ],
    name: "Driver Rack Venu 360",
    description:
      "Doublesub / 18 Inch / 4000watt / plywood / 100 coil /8 Ohms/ Passive sub",
    price: 2200000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "equalizer",
      "driver rack",
      "venue 360",
      "audio processor",
      "eq",
      "sound processing",
      "frequency control",
      "audio equipment",
      "venue",
    ],
    brand: "rave",
  },
  {
    id: 39,
    category: "equalizer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573506/Amplifier/e4_cdx3tv.png",
    ],
    name: "DBX-PA2",
    description:
      "Doublesub / 18 Inch / 4000watt / plywood / 100 coil /8 Ohms/ Passive sub",
    price: 2000000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "equalizer",
      "dbx",
      "pa2",
      "audio processor",
      "eq",
      "sound processing",
      "frequency control",
      "audio equipment",
      "pa system",
    ],
    brand: "rave",
  },
  {
    id: 40,
    category: "equalizer",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573509/Amplifier/e5_a7glt6.png",
    ],
    name: "DBX-266XL",
    description:
      "Doublesub / 18 Inch / 4000watt / plywood / 100 coil /8 Ohms/ Passive sub",
    price: 2200000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "equalizer",
      "dbx",
      "266xl",
      "audio processor",
      "eq",
      "sound processing",
      "frequency control",
      "audio equipment",
      "compressor",
    ],
    brand: "rave",
  },
  {
    id: 41,
    category: "linearray",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573767/Amplifier/la1_a7ewku.png",
    ],
    name: "SP-4",
    description: "15 Inch / 2000watt / Pure Acostic / 100 coil /Big magnet",
    price: 365000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "line array",
      "15 inch",
      "2000 watt",
      "pure acoustic",
      "100 coil",
      "big magnet",
      "speaker array",
      "sound system",
      "audio equipment",
      "live sound",
    ],
    brand: "soundprince",
  },
  {
    id: 42,
    category: "linearray",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573770/Amplifier/la2_pequun.png",
    ],
    name: "SP-415",
    description: "15 Inch / 4000watt / Pure Acostic / 100 coil /Double magnet",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "line array",
      "15 inch",
      "4000 watt",
      "pure acoustic",
      "100 coil",
      "double magnet",
      "high power",
      "speaker array",
      "professional audio",
      "concert sound",
    ],
    brand: "soundprince",
  },
  {
    id: 43,
    category: "linearray",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573770/Amplifier/la3_aff5ge.png",
    ],
    name: "SP-515",
    description: "15 Inch / 4800watt / Pure Acostic / 100 coil /Big magnet",
    price: 2000000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "line array",
      "15 inch",
      "4800 watt",
      "pure acoustic",
      "100 coil",
      "big magnet",
      "high power",
      "speaker array",
      "professional sound",
      "live performance",
    ],
    brand: "soundprince",
  },
  {
    id: 44,
    category: "linearray",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573772/Amplifier/la4_f82rjd.png",
    ],
    name: "SP215SD",
    description: "15 Inch / 2000watt / Pure Acostic / 100 coil /Big magnet",
    price: 365000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "line array",
      "15 inch",
      "2000 watt",
      "pure acoustic",
      "100 coil",
      "big magnet",
      "speaker array",
      "sound system",
      "audio equipment",
      "live sound",
    ],
    brand: "soundprince",
  },
  {
    id: 45,
    category: "linearray",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573774/Amplifier/la5_zs3wew.png",
    ],
    name: "SP28",
    description: "15 Inch / 4800watt / Pure Acostic / 100 coil /Double magnet",
    price: 1500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "line array",
      "15 inch",
      "4800 watt",
      "pure acoustic",
      "100 coil",
      "double magnet",
      "high power",
      "speaker array",
      "professional audio",
      "concert sound",
    ],
    brand: "soundprince",
  },
  {
    id: 46,
    category: "microphone",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752574403/Amplifier/zebra-wall-bracket-1537_pk3dtt.png",
    ],
    name: "SP4",
    description: "sound breaker mic / 100% wave /Big coverage",
    price: 68000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "microphone",
      "sound breaker",
      "100% wave",
      "big coverage",
      "mic",
      "vocal",
      "recording",
      "audio input",
      "sound capture",
      "live performance",
    ],
    brand: "rave",
  },
  {
    id: 47,
    category: "microphone",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752574405/Amplifier/1537_svoccu.png",
    ],
    name: "SP4",
    description: "sound breaker mic / 100% wave /Big coverage",
    price: 68000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "microphone",
      "sound breaker",
      "100% wave",
      "big coverage",
      "mic",
      "vocal",
      "recording",
      "audio input",
      "sound capture",
      "live performance",
    ],
    brand: "rave",
  },
  {
    id: 48,
    category: "microphone",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752574397/Amplifier/3_kvvdwk.png",
    ],
    name: "MIC",
    description: "sound breaker mic / 100% wave /Big coverage",
    price: 78000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "microphone",
      "sound breaker",
      "100% wave",
      "big coverage",
      "mic",
      "vocal",
      "recording",
      "audio input",
      "sound capture",
      "live performance",
    ],
    brand: "rave",
  },
  {
    id: 49,
    category: "drum",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752574052/Amplifier/d1_am11i7.png",
    ],
    name: "White Drum",
    description: "4 full set of Drums (complete set)",
    price: 300000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "drum set",
      "white drum",
      "4 piece",
      "complete set",
      "percussion",
      "drum kit",
      "musical instrument",
      "rhythm",
      "band equipment",
      "acoustic drums",
    ],
    brand: "rave",
  },
  {
    id: 50,
    category: "drum",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573914/Amplifier/purple_bnj69q.png",
    ],
    name: "Purple Drum",
    description: "4 full set of Drums (complete set)",
    price: 400000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "drum set",
      "purple drum",
      "4 piece",
      "complete set",
      "percussion",
      "drum kit",
      "musical instrument",
      "rhythm",
      "band equipment",
      "acoustic drums",
    ],
    brand: "rave",
  },
  {
    id: 51,
    category: "drum",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752573914/Amplifier/zebra-wall-bracket-1537_sunpc7.png",
    ],
    name: "Gold Drum",
    description: "4 full set of Drums (complete set)",
    price: 500000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "drum set",
      "gold drum",
      "4 piece",
      "complete set",
      "percussion",
      "drum kit",
      "musical instrument",
      "rhythm",
      "band equipment",
      "acoustic drums",
      "premium",
    ],
    brand: "rave",
  },
  {
    id: 52,
    category: "compressor",
    image: [
      "https://res.cloudinary.com/dmaag3pvx/image/upload/v1752574102/Amplifier/c1_vncaxf.png",
    ],
    name: "SP-266X",
    description: "15 Inch / 2000watt / Pure Acostic / 100 coil /Big magnet",
    price: 365000,
    stockQuantity: 3,
    discount: 2000,
    keyword: [
      "compressor",
      "audio compressor",
      "sound processing",
      "dynamic range",
      "audio equipment",
      "signal processing",
      "studio equipment",
      "sound control",
      "audio gear",
    ],
    brand: "soundprince",
  },
];
