export const products: string[] = [
  "AMP Rack",
  "Amplifier",
  "Audio Link",
  "Combo",
  "Compressor",
  "Conference Mic",
  "Digital Mixer",
  "Dj Controller",
  "Double Sub",
  "Drum",
  "Energy",
  "Equalizer",
  "Flat Mixer",
  "Floor Monitor",
  "Full Range Speaker",
  "Guitar",
  "Home Theatre",
  "Line Array",
  "Live Mixer",
  "Mic Antenna",
  "Microphone Stand",
  "Mixer Amp",
  "Naked Speaker",
  "Piano",
  "Power Surge",
  "Powered Speaker",
  "Processor",
  "Public Address",
  "Single Speaker",
  "Single Sub",
  "Speaker Management",
  "Speaker Stand",
  "Studio Microphone",
  "Wind Instruments",
  "Wired Microphone",
  "Wireless Microphone",
  "Powered Monitor",
];
export const brand: string[] = [
  "Soundprince",
  "JBL",
  "Mackkie",
  "High class",
  "Fdb",
  "Behringer",
  "Infinity",
  "Big sound",
  "Yamaha",
  "Amaz",
  "Dbass",
  "Dbx",
  "Ariz sound",
  "Virgin sound",
];

export const HeroObject = products.map((item) => ({
  title: item,
  product: item.toLowerCase(),
}));
